[package]
name = "wallet_socket_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anychain-core = "0.1.3"
anychain-ethereum = "0.1.7"
base64 = "0.21.5"
libsecp256k1 = "0.7.1"
rand = "0.8.5"
