[package]
name = "backoff_retry"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
backoff = "0.4.0"
reqwest = { version = "0.12", features = ["blocking"] }
