name: Rust CI Release

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-gnu

      - name: Install dependencies for cross-compiling to Linux
        run: sudo apt-get install -y gcc-multilib

      - name: Build for Linux
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --bin rayon_cli --target x86_64-unknown-linux-gnu

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            ${{ env.CI_TAG }} rayon_cli
          files: |
            target/x86_64-unknown-linux-gnu/release/rayon_cli
