name: Rust CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Rust
      uses: actions/setup-rust@v1
      with:
        rust-version: 1.68.0
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --verbose
